# Generated by Django 3.2.9 on 2021-11-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='desc',
        ),
    ]
